services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./todo-api/backend
    ports:
      - "8000:3000"
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    build: ./todo-api/frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db_data: